name: Run PHP Unit tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  run-automated-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Go to branch
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: php-actions/composer@v6
      - name: Run tests
        uses: php-actions/phpunit@v9.5.0
